# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#top-level-configuration

run:
  prefix: ""
  name: "baseline-3H"
  scenarios:
    enable: false
    file: config/scenarios.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true
  use_shadow_directory: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

scenario:
  clusters:
  - 39
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons:
  # - 2025
  - 2030
  # - 2035
  # - 2040

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'XK']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#snapshots
snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: 'left'

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: auto
  retrieve_databundle: true
  retrieve_cost_data: true
  build_cutout: false
  retrieve_cutout: false
  drop_leap_day: true
  certificate: true # [true, false ] If true, model the guarantee of origin

clustering:
  temporal:
    resolution_sector: 3H

sector:
  co2_network: false
  H2_network: false
  gas_network: false

strip_network:
  enable: true
  # by_country: false
  merge_load: true
  snapshots_start: false
  snapshots_end: false

certificate:
  plant_carriers: ["offwind", "offwind-ac", "offwind-dc", "offwind-float", "onwind", "ror", "hydro", "urban central solid biomass CHP", "geothermal", "solar", "solar-hsat", "solar rooftop", "nuclear"]
  plant_status: ["new", "existing"] # ["new", "existing"] if you include all (both new or existing), or only new powerplants
  max_plant_lifetime_as_new: 10
  plant_grouping: ["carrier", "status"] # [] or ["carrier", "status"]: Each generator are disaggregated by ...
  bus_grouping: [] # [] or ["carrier", "status"]: Each supply bus are disaggregated by ...
  aib_filepath: "data/AIB_monthly_data.csv"
  storage_carriers: ["battery", "H2 Store"]

  background_demand:
    enable: true
    scope: global # Cannot set scope to national due to many countries GO Demand exceeds national electricity demand. 
    supply_filter:
      country: ['AT', 'BE', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'NL', 'NO', 'PT', 'RS', 'SE', 'SI', 'SK']
      status: false
      carrier: false
    market_name: "AIB"
    go_profile: historical # {"historical", "total_daily_avg", "total", "baseload"}
    energy_matching: 100 # in percent relative to historical GO demand
    hourly_matching: 0

  new_demand:
    enable: true
    scope: national # {national, global}
    supply_filter:
      country: false
      status: false
      carrier: false
    market_name: ""
    go_profile: total # {"total_daily_avg", "total", "baseload"}
    energy_matching: 10 # in percent relative to country electricity load
    hourly_matching: 90 # 80 # in percent    

  map:
    supply: [-0.5, -0.5]
    background_demand: [0.5, -0.5]
    new_demand: [0.5, 0.5]
    market: [0, 0]
    market AIB: [0, 0.5]

overwrite_years:
  2030:
    # certificate:
    #   new_demand:
    #     energy_matching: 10
