# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#top-level-configuration

run:
  prefix: ""
  name: "multi-year-it"
  scenarios:
    enable: false
    file: config/scenarios.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true
  use_shadow_directory: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

scenario:
  clusters:
  - 3
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons:
  - 2025
  - 2030
  - 2035

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries: ['IT'] #['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'XK']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#snapshots
snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: 'left'

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: auto
  retrieve_databundle: true
  retrieve_cost_data: true
  build_cutout: false
  retrieve_cutout: false
  drop_leap_day: true
  certificate: true  # [true, false ] If true, model the guarantee of origin

certificate:
  scope: national # {national, global}
  plant_carriers: ["offwind", "offwind-ac", "offwind-dc", "offwind-float", "onwind", "ror", "hydro", "urban central solid biomass CHP", "geothermal", "solar", "solar-hsat", "solar rooftop", "nuclear"]
  plant_status: ["new", "existing"] # ["new", "existing"] if you include all (both new or existing), or only new powerplants
  max_plant_lifetime_as_new: 10
  plant_grouping: ["country", "carrier", "status"]

  strategy: vol-match
  energy_matching: 10 # in percent
