# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

# ===================== Baseline =====================
# ====================================================

# no confounding factors towards decarbonization
baseline-3H:
  enable:
    certificate: false

# base CO2 prices
baseline-co2-price-3H:
  enable:
    certificate: false

  overwrite_years:
    2025:
      costs:
        emission_prices:
          co2: 53
    2030:
      costs:
        emission_prices:
          co2: 108
    2035:
      costs:
        emission_prices:
          co2: 112
    2040:
      costs:
        emission_prices:
          co2: 115

# low CO2 prices
baseline-co2-price-low-3H:
  enable:
    certificate: false

  overwrite_years:
    2025:
      costs:
        emission_prices:
          co2: 12
    2030:
      costs:
        emission_prices:
          co2: 12
    2035:
      costs:
        emission_prices:
          co2: 19
    2040:
      costs:
        emission_prices:
          co2: 27

# high CO2 prices
baseline-co2-price-high-3H:
  enable:
    certificate: false

  overwrite_years:
    2025:
      costs:
        emission_prices:
          co2: 108
    2030:
      costs:
        emission_prices:
          co2: 108
    2035:
      costs:
        emission_prices:
          co2: 139
    2040:
      costs:
        emission_prices:
          co2: 159

# only existing AIB GO Market factors towards decarbonization
baseline-AIB-3H:
  certificate:
    background_demand:
      enable: true